server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false       # 关闭自我保护
    eviction-interval-timer-in-ms: 4000   # 清理间隔（默认60 * 1000）
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: famous-cloud-server

#RPC
rpc:
  host: localhost
  port: 9999
  rpc-type: Thrift

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      cors:
        allowed-origins: "*"
        allowed-methods: "*"


turbine:
  app-config: famous-login,famous-game,famous-battle
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream
